### ISSUE TITLE
URL issue missed by urlchecker

### ISSUE THREAD

**Issue by malcolmbarrett** [r-lib/urlchecker#25]
Got dinged by CRAN on a URL issue missed by urlchecker: https://win-builder.r-project.org/incoming_pretest/ymlthis_0.1.6_20220624_201807/Debian/00check.log

```
Found the following (possibly) invalid URLs:
  URL: https://tug.org/FontCatalogue/
    From: man/yml_latex_opts.Rd
          inst/doc/yaml-fieldguide.html
    Status: Error
    Message: server certificate verification failed. CAfile: none CRLfile: none
```

This could be a one-off issue, but filing just in case

**Comment by gaborcsardi** [comment]
What is wrong with that URL? It seems to have a valid vertificate.

**Comment by malcolmbarrett** [comment]
🤷 

I did not see this on winbuilder, by the way, so I don't know what to make of it

**Comment by gaborcsardi** [comment]
I suspect this is some configuration issue on the machine that produced it, but maybe you can try asking CRAN what is wrong with it if not.

**Comment by malcolmbarrett** [comment]
Well, CRAN accepted the submission without comment on the URL so 🤷 🤷 . Hopefully a one-time thing. Thanks, anyway!
