### ISSUE TITLE
Is there a GHA workflow example?

### ISSUE THREAD

**Issue by maelle** [r-lib/urlchecker#3]

**Comment by jimhester** [comment]
No, I generally just use this locally before a release. I am not sure it would be worth using on GitHub Actions, but maybe...

**Comment by maelle** [comment]
I was wondering whether one should run it on a schedule, but maybe it's not worth it indeed.

**Comment by dpprdan** [comment]
To me this is similar to code linting. You can do it locally (and use(this) reminders before CRAN submission) but it's one of the tasks that can just as well be automated.
