### ISSUE TITLE
Doesn't preserve fragments

### ISSUE THREAD

**Issue by hadley** [r-lib/urlchecker#9]
The suggested replacement for `https://www.tidyverse.org/lifecycle/#maturing` is `https://lifecycle.r-lib.org/articles/stages.html`, which loses the url fragment

**Comment by jimhester** [comment]
Yes, but this is due to the code in tools, I am not sure we should change this, in general I am trying to make sure our code stays as close to CRANs as we realistically can so we can reproduce their results.

**Comment by hadley** [comment]
It is objectively wrong though, because following a redirected link will preserve the fragment.  Maybe another patch to R-core?

**Comment by jimhester** [comment]
yeah I could look into it, will keep this open.

**Comment by gaborcsardi** [comment]
The standard says that the fragment should be preserved if the new url does not have a fragment: https://www.rfc-editor.org/rfc/rfc7231#section-7.1.2

**Comment by gaborcsardi** [comment]
Submitted patch to base R: https://bugs.r-project.org/show_bug.cgi?id=18316

I'll add this to urlchecker, nevertheless. If base is not patched then we'll need to update `urltools.R` from R's SVN more carefully in the future.

**Comment by gaborcsardi** [comment]
This is now fixed in (tomorrow's) R-devel:
https://github.com/wch/r-source/commit/2dc39e30df390b48218f9b062f829bbc64e347b2
